# Generated by Django 5.0.4 on 2024-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_profile_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
