# Generated by Django 5.0.4 on 2024-05-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProTwo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_mame',
            new_name='first_name',
        ),
    ]
